/* 
******************************************
SQL Project by Ruchi Asthana
******************************************
*/


/*
-------------------------------------------------------------------------------------
Q1. Display all completed orders along with customer name and restaurant name.
-------------------------------------------------------------------------------------
*/
SELECT 
    o.order_id,
    c.customer_name,
    r.restaurant_name,
    o.order_status
FROM orders o
JOIN customers c 
    ON o.customer_id = c.customer_id
JOIN restaurants r 
    ON o.restaurant_id = r.restaurant_id
WHERE o.order_status = 'completed';

/*
--------------------------------------------------------------------------------------
Q2. Find the total revenue generated by each restaurant.
--------------------------------------------------------------------------------------
*/
SELECT 
    r.restaurant_id,
    r.restaurant_name,
    SUM(o.order_amount) AS total_revenue
FROM restaurants r
JOIN orders o 
    ON r.restaurant_id = o.restaurant_id
WHERE o.order_status = 'completed'
GROUP BY 
    r.restaurant_id,
    r.restaurant_name
ORDER BY 
    total_revenue DESC;

/*
--------------------------------------------------------------------------------------
Q3. Show the total number of orders placed by each customer.
--------------------------------------------------------------------------------------
*/
SELECT 
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY 
    c.customer_id,
    c.customer_name
ORDER BY 
    total_orders DESC;
    
/*
--------------------------------------------------------------------------------------
Q4. Find the average order amount for each city.
--------------------------------------------------------------------------------------
*/
SELECT 
    c.city,
    AVG(o.order_amount) AS avg_order_amount
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_status = 'completed'
GROUP BY 
    c.city
ORDER BY 
    avg_order_amount DESC;
    
/*
--------------------------------------------------------------------------------------
Q5. Categorize orders as Low, Medium, and High based on order amount.
--------------------------------------------------------------------------------------
*/
SELECT 
    order_id,
    customer_id,
    restaurant_id,
    order_amount,
    CASE 
        WHEN order_amount < 500 THEN 'Low'
        WHEN order_amount BETWEEN 500 AND 1500 THEN 'Medium'
        ELSE 'High'
    END AS order_category
FROM orders
WHERE order_status = 'completed';

/*
--------------------------------------------------------------------------------------
Q6. Display restaurants whose average order value is greater than the overall average order value.
--------------------------------------------------------------------------------------
*/
SELECT 
	r.restaurant_id,
    r.restaurant_name,
    AVG(o.order_amount) AS restaurant_avg_order_value,
    (
        SELECT AVG(order_amount)
        FROM orders
        WHERE order_status = 'completed'
    ) AS overall_avg_order_value
FROM restaurants r
JOIN orders o
    ON r.restaurant_id = o.restaurant_id
WHERE o.order_status = 'completed'
GROUP BY 
    r.restaurant_id,
    r.restaurant_name
HAVING
    AVG(o.order_amount) > (
        SELECT AVG(order_amount)
        FROM orders
        WHERE order_status = 'completed'
    )
ORDER BY restaurant_avg_order_value DESC;

/*
--------------------------------------------------------------------------------------
Q7. Find customers who have never placed any orders.
--------------------------------------------------------------------------------------
*/
SELECT 
    c.customer_id,
    c.customer_name
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY 
    c.customer_id,
    c.customer_name
HAVING
	count(o.order_id) = 0;
    
/*
--------------------------------------------------------------------------------------
Q8. Show the top 5 customers based on total spending.
--------------------------------------------------------------------------------------
*/
SELECT 
    c.customer_id,
    c.customer_name,
    SUM(o.order_amount) AS total_spending
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_status = 'completed'
GROUP BY 
    c.customer_id,
    c.customer_name
ORDER BY 
    total_spending DESC
LIMIT 5;

/*
--------------------------------------------------------------------------------------
Q9. Find the most frequently used payment method.
--------------------------------------------------------------------------------------
*/
SELECT 
    payment_method,
    COUNT(*) AS usage_count
FROM orders
WHERE order_status = 'completed'
GROUP BY payment_method
ORDER BY usage_count DESC
LIMIT 1;

/*
--------------------------------------------------------------------------------------
Q10. Calculate the running total of revenue by order date.
--------------------------------------------------------------------------------------
*/
SELECT
    order_date,
    SUM(order_amount) AS daily_revenue,
    SUM(SUM(order_amount)) OVER (
        ORDER BY order_date
    ) AS running_total_revenue
FROM orders
WHERE order_status = 'completed'
GROUP BY order_date
ORDER BY order_date;

/*
--------------------------------------------------------------------------------------
Q11. Rank restaurants based on total revenue generated.
--------------------------------------------------------------------------------------
*/
SELECT
    r.restaurant_id,
    r.restaurant_name,
    SUM(o.order_amount) AS total_revenue,
    RANK() OVER (
        ORDER BY SUM(o.order_amount) DESC
    ) AS revenue_rank
FROM restaurants r
JOIN orders o
    ON r.restaurant_id = o.restaurant_id
WHERE o.order_status = 'completed'
GROUP BY 
    r.restaurant_id,
    r.restaurant_name
ORDER BY 
    revenue_rank;
    
/*
--------------------------------------------------------------------------------------
Q12. Find the second highest order amount from the orders table. 
--------------------------------------------------------------------------------------
*/
SELECT DISTINCT order_amount
FROM orders
WHERE order_status = 'completed'
ORDER BY order_amount DESC
LIMIT 1 OFFSET 1;

/*
--------------------------------------------------------------------------------------
Q13. Find customers who placed more orders than the average number of orders per customer.
--------------------------------------------------------------------------------------
*/
SELECT 
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders,
    (
        SELECT AVG(order_count)
        FROM (
            SELECT COUNT(order_id) AS order_count
            FROM orders
            GROUP BY customer_id
        ) t
    ) AS avg_order_count
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY 
    c.customer_id,
    c.customer_name
HAVING 
    COUNT(o.order_id) > (
        SELECT AVG(order_count)
        FROM (
            SELECT COUNT(order_id) AS order_count
            FROM orders
            GROUP BY customer_id
        ) t
    )
ORDER BY total_orders DESC;

/*
--------------------------------------------------------------------------------------
Q14.Display the top 3 restaurants in each city based on total orders received. 
--------------------------------------------------------------------------------------
*/
SELECT
    city,
    restaurant_id,
    restaurant_name,
    total_orders,
    rank_in_city
FROM (
    SELECT
        r.city,
        r.restaurant_id,
        r.restaurant_name,
        COUNT(o.order_id) AS total_orders,
        DENSE_RANK() OVER (
            PARTITION BY r.city
            ORDER BY COUNT(o.order_id) DESC
        ) AS rank_in_city
    FROM restaurants r
    JOIN orders o
        ON r.restaurant_id = o.restaurant_id
    WHERE o.order_status = 'completed'
    GROUP BY 
        r.city,
        r.restaurant_id,
        r.restaurant_name
) t
WHERE rank_in_city <= 3
ORDER BY city, rank_in_city;

/*
--------------------------------------------------------------------------------------
Q15. Calculate month-wise revenue and show the previous month revenue.
--------------------------------------------------------------------------------------
*/
SELECT
    year(order_date) AS year, month(order_date) AS month,
    SUM(order_amount) AS monthly_revenue,
    LAG(SUM(order_amount)) OVER (
        ORDER BY year(order_date), month(order_date)
    ) AS previous_month_revenue
FROM orders
WHERE order_status = 'completed'
GROUP BY year(order_date), month(order_date)
ORDER BY year(order_date), month(order_date);

/*
-----------------END OF PROJECT--------------------------------------------------------------
*/

